### ISSUE TITLE
production Docker build error

### ISSUE THREAD

**Issue by wallento** [CircuitVerse/CircuitVerse#3304]
**Describe the bug**
When running the current Docker container from `ghcr.io/circuitverse/circuitverse:master` I observe the following error:

```
web_1       | /usr/src/app/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.3.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `has_noticed_notifications' for Project:Class (NoMethodError)
web_1       |   from /usr/src/app/app/models/project.rb:21:in `<class:Project>'
web_1       |   from /usr/src/app/app/models/project.rb:6:in `<main>'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:239:in `block (2 levels) in eager_load'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `ls'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:234:in `block in eager_load'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `synchronize'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `eager_load'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:318:in `each'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:318:in `eager_load_all'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `instance_exec'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:32:in `run'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:50:in `each'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:50:in `tsort_each_child'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `call'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:415:in `each_strongly_connected_component_from'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
web_1       |   from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/initializable.rb:60:in `run_initializers'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/application.rb:372:in `initialize!'
web_1       |   from /usr/src/app/config/environment.rb:5:in `<main>'
web_1       |   from config.ru:5:in `require_relative'
web_1       |   from config.ru:5:in `block in <main>'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:312:in `block in start'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:379:in `handle_profiling'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:311:in `start'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:38:in `start'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:143:in `block in perform'
web_1       |   from <internal:kernel>:90:in `tap'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/commands/server/server_command.rb:134:in `perform'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/command/base.rb:87:in `perform'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/command.rb:48:in `invoke'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.3.1/lib/rails/commands.rb:18:in `<main>'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
web_1       |   from /usr/src/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
web_1       |   from bin/rails:9:in `<main>'
```
I was able to pin it down to this commit: https://github.com/CircuitVerse/CircuitVerse/commit/c801c4215167e5f05e1ac8f1fbefc82bef42ac17 

This is also visible with the two buillds of this commit and the preceeding commit:

- image: ghcr.io/circuitverse/circuitverse@sha256:2dc6554f72a27b8c80dfe03de9314247978ab3acb1edcb7b1c35199d68ddf137 as built here: https://github.com/CircuitVerse/CircuitVerse/actions/runs/2984779794/jobs/4785460813
- working previous image: ghcr.io/circuitverse/circuitverse@sha256:2e97bbe528a5a8cc61a14ed1608c3b59de3aa7494d9f8abce4637850e325c32b as built here: https://github.com/CircuitVerse/CircuitVerse/actions/runs/2963606275/jobs/4742363731

**To Reproduce**
Run the docker container

**Expected behavior**
It should not crash

**Are you working on this issue? (Yes/No)**
I tried to, but have no clue what in the update causes this

**Comment by vedant-jain03** [comment]
cc @CircuitVerse/circuitverse-core-team

**Comment by tachyons** [comment]
This was caused after the rails upgrade which somehow caused noticed's ability to automatically be included in models, I fixed it on circuitverse side for now.

**Comment by tachyons** [comment]
@wallento We have a plan to improve the self hosting experience for circuit verse. Do you have 30 minute this month to talk about your use case and challenges ?

**Comment by wallento** [comment]
Hi, thats a great proposal. I am currently spinning it up for the upcoming semester and was quite successful. I will show you what we changed for our purpose and how we could benefit from some minor changes in our work to keep the fork up to date. Can you please drop me a mail at stefan.wallentowitz@hm.edu, thanks!
